"""Professional VAPT Report Generator Module"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.platypus import PageBreak
from datetime import datetime
import os

class VAPTReportGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom styles for the report"""
        self.styles.add(ParagraphStyle(
            name='CustomHeading1',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30
        ))
        self.styles.add(ParagraphStyle(
            name='CustomHeading2',
            parent=self.styles['Heading2'],
            fontSize=18,
            spaceAfter=20
        ))
        self.styles.add(ParagraphStyle(
            name='CustomNormal',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12
        ))
        self.styles.add(ParagraphStyle(
            name='CustomHeading3',
            parent=self.styles['Heading3'],
            fontSize=14,
            spaceAfter=10
        ))

    def generate_report(self, target_url: str, va_results: list, pt_results: dict, malware_results: list = None) -> str:
        """Generate a professional VAPT report, now including malware analysis results."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = os.path.join(self.output_dir, f"VAPT_Report_{timestamp}.pdf")
        
        doc = SimpleDocTemplate(
            filename,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )

        # Build the report content
        story = []
        
        # Cover Page
        self._add_cover_page(story, target_url)
        story.append(PageBreak())

        # Executive Summary
        self._add_executive_summary(story, va_results, pt_results)
        story.append(PageBreak())

        # Methodology
        self._add_methodology_section(story)
        story.append(PageBreak())

        # Vulnerability Assessment Findings
        self._add_va_findings(story, va_results)
        story.append(PageBreak())

        # Penetration Testing Findings
        self._add_pt_findings(story, pt_results)
        story.append(PageBreak())

        # Malware Analysis Section
        if malware_results:
            self._add_malware_analysis(story, malware_results)
            story.append(PageBreak())

        # Recommendations
        self._add_recommendations(story, va_results, pt_results)
        story.append(PageBreak())

        # Build the PDF
        doc.build(story)
        return filename

    def _add_cover_page(self, story: list, target_url: str):
        """Add the cover page"""
        # Add logo if available
        logo_path = os.path.join(os.path.dirname(__file__), "ui", "assets", "logo.png")
        if os.path.exists(logo_path):
            img = Image(logo_path, width=2*inch, height=2*inch)
            story.append(img)
            story.append(Spacer(1, 30))

        story.append(Paragraph("Vulnerability Assessment & Penetration Testing Report", self.styles["CustomHeading1"]))
        story.append(Spacer(1, 30))
        story.append(Paragraph(f"Target: {target_url}", self.styles["CustomNormal"]))
        story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}", self.styles["CustomNormal"]))
        story.append(Paragraph("Generated by AutoDAST", self.styles["CustomNormal"]))

    def _add_executive_summary(self, story: list, va_results: list, pt_results: dict):
        """Add the executive summary section"""
        story.append(Paragraph("Executive Summary", self.styles["CustomHeading1"]))
        
        # Calculate statistics
        total_vulns = len(va_results)
        severity_counts = {
            "Critical": len([v for v in va_results if v["severity"] == "Critical"]),
            "High": len([v for v in va_results if v["severity"] == "High"]),
            "Medium": len([v for v in va_results if v["severity"] == "Medium"]),
            "Low": len([v for v in va_results if v["severity"] == "Low"]),
            "Info": len([v for v in va_results if v["severity"] == "Info"])
        }

        summary = [
            ["Finding Category", "Count"],
            ["Critical Vulnerabilities", severity_counts["Critical"]],
            ["High Vulnerabilities", severity_counts["High"]],
            ["Medium Vulnerabilities", severity_counts["Medium"]],
            ["Low Vulnerabilities", severity_counts["Low"]],
            ["Informational Findings", severity_counts["Info"]]
        ]

        table = Table(summary, colWidths=[4*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 14),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(table)

    def _add_methodology_section(self, story: list):
        """Add the methodology section"""
        story.append(Paragraph("Methodology", self.styles["CustomHeading1"]))
        story.append(Paragraph("""
            The security assessment was conducted using a comprehensive approach that combines automated vulnerability scanning with manual penetration testing techniques. The methodology follows industry best practices and includes:
        """, self.styles["CustomNormal"]))

        methods = [
            "Automated Vulnerability Assessment using OWASP ZAP",
            "Port Scanning and Service Enumeration",
            "Directory and File Enumeration",
            "JavaScript Analysis for Client-side Vulnerabilities",
            "Manual Verification of Findings",
            "Risk Assessment and Prioritization"
        ]

        for method in methods:
            story.append(Paragraph(f"• {method}", self.styles["CustomNormal"]))

    def _add_va_findings(self, story: list, va_results: list):
        """Add the vulnerability assessment findings section"""
        story.append(Paragraph("Vulnerability Assessment Findings", self.styles["CustomHeading1"]))

        # Group findings by severity
        severities = ["Critical", "High", "Medium", "Low", "Info"]
        for severity in severities:
            findings = [v for v in va_results if v["severity"] == severity]
            if findings:
                story.append(Paragraph(f"{severity} Severity Findings", self.styles["CustomHeading2"]))
                for idx, finding in enumerate(findings, 1):
                    story.append(Paragraph(f"{idx}. {finding['name']}", self.styles["CustomHeading2"]))
                    story.append(Paragraph(f"OWASP Category: {finding.get('owasp_category', 'N/A')}", self.styles["CustomNormal"]))
                    story.append(Paragraph(f"Description: {finding['description']}", self.styles["CustomNormal"]))
                    story.append(Paragraph(f"URL: {finding['url']}", self.styles["CustomNormal"]))
                    if finding.get('cve'):
                        story.append(Paragraph(f"CVE: {finding['cve']}", self.styles["CustomNormal"]))
                    # Add Mitigation and Remediation section
                    mitigation = finding.get('mitigation')
                    remediation = finding.get('remediation')
                    if mitigation or remediation:
                        story.append(Paragraph("Mitigation and Remediation Steps:", self.styles["CustomHeading3"]))
                        if mitigation:
                            story.append(Paragraph(f"Immediate Mitigation: {mitigation}", self.styles["CustomNormal"]))
                        if remediation:
                            story.append(Paragraph(f"Long-term Remediation: {remediation}", self.styles["CustomNormal"]))
                    story.append(Spacer(1, 20))

    def _add_pt_findings(self, story: list, pt_results: dict):
        """Add the penetration testing findings section (with vulnerable links and screenshots)."""
        story.append(Paragraph("Penetration Testing Findings", self.styles["CustomHeading1"]))
        findings_present = False
        # Add recon findings
        if "recon" in pt_results:
            findings_present = True
            story.append(Paragraph("Reconnaissance Findings", self.styles["CustomHeading2"]))
            recon = pt_results["recon"]
            if "subdomains" in recon:
                story.append(Paragraph("Discovered Subdomains:", self.styles["CustomNormal"]))
                for subdomain in recon["subdomains"]:
                    story.append(Paragraph(f"• {subdomain}", self.styles["CustomNormal"]))
                story.append(Spacer(1, 10))
            if "ports" in recon:
                story.append(Paragraph("Open Ports and Services:", self.styles["CustomNormal"]))
                for port, service in recon["ports"].items():
                    story.append(Paragraph(f"• Port {port}: {service}", self.styles["CustomNormal"]))
                story.append(Spacer(1, 10))
            if "directories" in recon:
                story.append(Paragraph("Discovered Directories:", self.styles["CustomNormal"]))
                for directory in recon["directories"]:
                    story.append(Paragraph(f"• {directory}", self.styles["CustomNormal"]))
                story.append(Spacer(1, 10))
        # Add additional pentest findings
        if "vulnerabilities" in pt_results and pt_results["vulnerabilities"]:
            findings_present = True
            story.append(Paragraph("Additional Vulnerabilities", self.styles["CustomHeading2"]))
            for vuln in pt_results["vulnerabilities"]:
                story.append(Paragraph(f"• {vuln}", self.styles["CustomNormal"]))
        # Add exploitation results if available
        exploitation = pt_results.get("exploitation", [])
        if exploitation:
            findings_present = True
            story.append(Paragraph("Automated Exploitation Results", self.styles["CustomHeading2"]))
            for idx, exp in enumerate(exploitation, 1):
                finding = exp.get('finding', {})
                exploit_result = exp.get('exploit_result', {})
                evidence = exp.get('evidence', '')
                screenshot = exp.get('screenshot')
                vuln_url = finding.get('url', 'N/A')
                story.append(Paragraph(f"{idx}. Vulnerable Link: {vuln_url}", self.styles["CustomHeading3"]))
                if evidence:
                    story.append(Paragraph(f"Evidence: {evidence}", self.styles["CustomNormal"]))
                if exploit_result:
                    story.append(Paragraph(f"Exploit Output:", self.styles["CustomNormal"]))
                    output = exploit_result.get('stdout', '')
                    if output:
                        story.append(Paragraph(f"<pre>{output[:1000]}</pre>", self.styles["CustomNormal"]))
                if screenshot and os.path.exists(screenshot):
                    story.append(Paragraph("Screenshot:", self.styles["CustomNormal"]))
                    try:
                        img = Image(screenshot, width=5*inch, height=3*inch)
                        story.append(img)
                    except Exception:
                        story.append(Paragraph("[Screenshot could not be loaded]", self.styles["CustomNormal"]))
                story.append(Spacer(1, 20))
        if not findings_present:
            story.append(Paragraph("No penetration testing findings available.", self.styles["CustomNormal"]))

    def _add_malware_analysis(self, story: list, malware_results: list):
        """Add a malware analysis section to the report."""
        story.append(Paragraph("Malware Analysis Results", self.styles["CustomHeading1"]))
        if not malware_results:
            story.append(Paragraph("No malware analysis results available.", self.styles["CustomNormal"]))
            return
        for idx, result in enumerate(malware_results, 1):
            story.append(Paragraph(f"{idx}. Target: {result.get('target', 'N/A')}", self.styles["CustomHeading2"]))
            if result.get('error'):
                story.append(Paragraph(f"Error: {result['error']}", self.styles["CustomNormal"]))
                continue
            stats = result.get('stats', {})
            summary = f"Malicious: {stats.get('malicious', 0)}, Suspicious: {stats.get('suspicious', 0)}, Harmless: {stats.get('harmless', 0)}"
            story.append(Paragraph(f"Detection Summary: {summary}", self.styles["CustomNormal"]))
            # Show top detection results
            detections = result.get('last_analysis_results', {})
            if detections:
                story.append(Paragraph("Detection Results:", self.styles["CustomNormal"]))
                for vendor, det in list(detections.items())[:10]:
                    story.append(Paragraph(f"- {vendor}: {det.get('category', 'unknown').title()} - {det.get('result', 'N/A')}", self.styles["CustomNormal"]))
            story.append(Spacer(1, 10))

    def _add_recommendations(self, story: list, va_results: list, pt_results: dict):
        """Add the recommendations section"""
        story.append(Paragraph("Recommendations", self.styles["CustomHeading1"]))
        
        # Group recommendations by severity
        recommendations = {}
        for finding in va_results:
            severity = finding["severity"]
            if severity not in recommendations:
                recommendations[severity] = []
            if "recommendation" in finding:
                recommendations[severity].append(finding["recommendation"])

        for severity in ["Critical", "High", "Medium", "Low"]:
            if severity in recommendations and recommendations[severity]:
                story.append(Paragraph(f"{severity} Priority Recommendations", self.styles["CustomHeading2"]))
                for rec in recommendations[severity]:
                    story.append(Paragraph(f"• {rec}", self.styles["CustomNormal"]))
                story.append(Spacer(1, 10))

        # Add general security recommendations
        story.append(Paragraph("General Security Recommendations", self.styles["CustomHeading2"]))
        general_recs = [
            "Implement a regular vulnerability scanning and patching program",
            "Conduct regular security awareness training for development teams",
            "Implement secure coding practices and code review processes",
            "Maintain an up-to-date incident response plan",
            "Regular backup and disaster recovery testing"
        ]
        for rec in general_recs:
            story.append(Paragraph(f"• {rec}", self.styles["CustomNormal"])) 